---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: q-prep-config
data:
  ASPNETCORE_URLS: "http://0.0.0.0:8080"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_ADDRESS: "redasaad010260@gmail.com"
  jwt-audience: "https://localhost:7243/"
  jwt-issuer: "https://localhost:7243/"  
  jwt-expire: "2" 


  
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: q-prep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: q-prep
  template:
    metadata:
      labels:
        app: q-prep
    spec:
      containers:
      - name: q-prep
        image: redasaad123/q-prep:latest
        volumeMounts:
          - name: q-prep-volume
            mountPath: /app/wwwroot
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: ASPNETCORE_URLS

        - name: email-confg__Host
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: EMAIL_HOST

        - name: email-confg__Port
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: EMAIL_PORT
            
        - name: email-confg__Email
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: EMAIL_ADDRESS
            
        - name: email-confg__Password
          valueFrom:
            secretKeyRef:
              name: q-prep-secret
              key: EMAIL_PASSWORD

        - name: ConnectionStrings__ProdcutionConnection
          valueFrom:
            secretKeyRef:
              name: q-prep-secret
              key: ConnectionStrings

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: q-prep-secret
              key: JWT_SECRET
        
        - name: jwt__AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: jwt-audience

        - name: jwt__ISSUER
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: jwt-issuer

        - name: jwt__DurationInDays
          valueFrom:
            configMapKeyRef:
              name: q-prep-config
              key: jwt-expire
        
      volumes:
        - name: q-prep-volume
          persistentVolumeClaim:
            claimName: q-prep-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: q-prep-service
spec:
  type: ClusterIP
  selector:
    app: q-prep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q-prep-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  
spec:
  ingressClassName: nginx
  rules:
  - host: qprep.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: q-prep-service
            port:
              number: 8080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: q-prep-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ubuntu/q-prep

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: q-prep-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


