apiVersion: apps/v1
kind: Deployment
metadata:
  name: q-prep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: q-prep
  template:
    metadata:
      labels:
        app: q-prep
    spec:
      containers:
      - name: q-prep
        image: redasaad123/q-prep:latest
        # volumeMounts:
        #   - name: q-prep-volume
        #     mountPath: /app/wwwroot
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8080"

      # volumes:
      #   - name: q-prep-volume
      #     persistentVolumeClaim:
      #       claimName: q-prep-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: q-prep-service
spec:
  type: ClusterIP
  selector:
    app: q-prep
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: q-prep-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  
spec:
  ingressClassName: nginx
  rules:
  - host: qprep.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: q-prep-service
            port:
              number: 8080
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: q-prep-pv
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /home/ubuntu/q-prep

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: q-prep-pvc
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi


