---
# install Python
- name: Install Python 3.10 and set as default
  import_tasks: templatesTasks/install-Python.yml


# install Docker 
- name: Install Docker on VM
  import_tasks: templatesTasks/Docker.yml

# install Kubernetes components
- name: Install Kubernetes components on VM
  import_tasks: templatesTasks/K8s.yml



