# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Project 

on:
  repository_dispatch:
    types: [CI-completed]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IP_Master: ${{ secrets.IP_MASTER }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          if [ -z "${{ env.IP_Master }}" ]; then
            echo "Missing IP_MASTER secret"
            exit 1
          fi
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -T 5 -H ${{ env.IP_Master }} >> ~/.ssh/known_hosts || true

      - name: Wait for SSH
        timeout-minutes: 5
        run: |
          MAX_RETRIES=60
          RETRY_COUNT=0
          until ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -q ubuntu@${{ env.IP_Master }} exit; do
            echo "Waiting for SSH to be available..."
            sleep 5
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "❌ SSH connection timeout after $((MAX_RETRIES * 5)) seconds"
              exit 1
            fi
          done
          echo "✅ SSH connection established"


      - name: Create Kubernetes Secret
        run: |
          cat <<EOF > secret.yml
          apiVersion: v1
          kind: Secret
          metadata: 
            name: q-prep-secret
          type: Opaque 
          stringData:
            EMAIL_PASSWORD: "${{ secrets.EMAIL_PASSWORD }}"
            ConnectionStrings: "${{ secrets.DB_CONNECTION_STRING }}" 
            JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          EOF
        
      - name: Move the file to Master Server
        run: |
          scp -i ~/.ssh/id_rsa Devops/K8s/main.yml ubuntu@${{ env.IP_Master }}:/home/ubuntu/k8s-main.yml
          scp -i ~/.ssh/id_rsa Devops/K8s/secret.yml ubuntu@${{ env.IP_Master }}:/home/ubuntu/secret.yml

      # - name: Clean up PV and PVC
      #   run: |
      #     ssh -i ~/.ssh/id_rsa ubuntu@${{ env.IP_Master }} 
      #     kubectl delete pvc q-prep-pvc --ignore-not-found=true
      #     kubectl delete pv q-prep-pv --ignore-not-found=true

      - name: Clean up Pods
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.IP_Master }} 
          kubectl delete pods -l app=q-prep --ignore-not-found=true

      - name: Apply secret manifest
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.IP_Master }} 
          kubectl apply -f /home/ubuntu/secret.yml
       
      - name: Apply Kubernetes Manifest
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ env.IP_Master }} 
          kubectl apply -f /home/ubuntu/k8s-main.yml
          

          
         




