# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name:  CI Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'Projects/**'
      - '.github/workflows/CI.yml'
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore Q-Prep.sln

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@v2
        with:
          project: 'Q-Prep'
          path: '.'
          format: 'XML'
          args: >
            --enableExperimental

      - name: Publish OWASP Dependency Check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: owasp-dependency-check-report
          path: reports/
      
      - name: Build
        run: dotnet build Q-Prep.sln --configuration Release --no-restore

      - name: SonarQube Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Q-Prep
            -Dsonar.organization=soneratech
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io







